name: Push Docker Images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build & Publish API to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: galaxyfuture/bridgx-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: API.Dockerfile
        tags: "latest"

    - uses: actions/checkout@master
    - name: Build & Publish Scheduler to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: galaxyfuture/bridgx-scheduler
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: SCHEDULER.Dockerfile
        tags: "latest"

---
name: Publish Tagged Version

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build & Publish API to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: galaxyfuture/bridgx-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: API.Dockerfile
          tags: "latest,${{ github.ref }}"

      - uses: actions/checkout@master
      - name: Build & Publish Scheduler to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: galaxyfuture/bridgx-scheduler
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: SCHEDULER.Dockerfile
          tags: "latest,${{ github.ref }}"